### ISSUE TITLE
Support for navigating catalog from Rancher

### ISSUE THREAD

**Issue by sanel** [HYmian/hadoop#2]
Hi @HYmian,

First of all, thanks for the work you've made here. Is it possible to make repository discoverable from Rancher UI, by setting [custom catalog](https://docs.rancher.com/rancher/v1.1/en/catalog/) to points to you repository?

Also, what is the state of rancher/docker files right now; do you consider them production ready?

Thanks!

**Comment by HYmian** [comment]
sorry, please don't do that for some reason.
I may close this repository after a time, but you can use it now.
and I don't use them for production now.

Thank you for like them
